### ISSUE TITLE
LICENSE should be in the top level

### ISSUE THREAD

**Issue by admjgptw1357** [ojjiy/line_profiler_extension#8]

**Comment by ojjiy** [comment]
I'm not sure where to place LICENSE since I'm not familiar with rules in showing it.
In my understanding, the files under `./inputs` are licensed as shown in LICENSE and I don't give any LICENSE for the contents of the parent folder.
Is it right to place LICENSE at the top level in such a case?

**Comment by admjgptw1357** [comment]
ライセンスの置かれている場所を確認する
多くの場合、ライセンステキストはリポジトリのルートにある LICENSE.txt (または LICENSE.md) というファイルに書かれています。 Hubot の例をこちらに示します。
https://help.github.com/ja/articles/licensing-a-repository

**Comment by admjgptw1357** [comment]
sorry I misunderstood.
Please ignore my suggestion. This is correct
