### ISSUE TITLE
requirements.txt should contain line-profiler

### ISSUE THREAD

**Issue by admjgptw1357** [ojjiy/line_profiler_extension#9]

**Comment by ojjiy** [comment]
This tool itself does not seem to require line-profiler
(While this tool is the sub-tool of line-profiler :P ).
Since line-profiler cannot be installed using pip currently, I want to avoid including line-profiler in the requirements.txt.

**Comment by admjgptw1357** [comment]
I don't think so cuz some time the only union of the multiple results is required w/o executing the line-profiler.

If you don't want to put it as a dependency, you shouldn't call line-profiler in script.py, I think.

**Comment by ojjiy** [comment]
As for removing script.py, I agree with your opinion and will remove in the next commitment.
